const TE_SR_COLUMNS = [
  { COLUMN_IDX: 1, COLUMN_ID: 'REQUEST_ID', COLUMN_TITLE: 'Case Id' },
  { COLUMN_IDX: 2, COLUMN_ID: 'SERVICE_CATEGORY', COLUMN_TITLE: 'Service Category' },
  { COLUMN_IDX: 3, COLUMN_ID: 'REQ_REP_NO', COLUMN_TITLE: 'Request Id / Report Number' },
  { COLUMN_IDX: 4, COLUMN_ID: 'CREATION_DATE', COLUMN_TITLE: 'Creation Date' },
  { COLUMN_IDX: 5, COLUMN_ID: 'STATUS', COLUMN_TITLE: 'Status' },
  { COLUMN_IDX: 6, COLUMN_ID: 'ENTITY', COLUMN_TITLE: 'Entity' },
  { COLUMN_IDX: 7, COLUMN_ID: 'ENTITY_CODE', COLUMN_TITLE: 'Entity Code' },
  { COLUMN_IDX: 8, COLUMN_ID: 'CREATED_BY', COLUMN_TITLE: 'Raised By' },
  { COLUMN_IDX: 9, COLUMN_ID: 'CREATED_BY_NAME', COLUMN_TITLE: 'Employee Name' },
  { COLUMN_IDX: 10, COLUMN_ID: 'CREATED_BY_EMAIL', COLUMN_TITLE: 'Raised Email' },
  { COLUMN_IDX: 11, COLUMN_ID: 'ASSIGNED_GROUP', COLUMN_TITLE: 'Assigned Group' },
  { COLUMN_IDX: 12, COLUMN_ID: 'AGING_DAYS', COLUMN_TITLE: 'Aging Tickets (Days)' },
]

module.exports = { TE_SR_COLUMNS }
